# Name override instead of fullname (llm-ingestor)
nameOverride: 'llm-ingestor'

# Docker Hub credentials secret
secrets:
  dockerhubconfigjson: ''

env:
  KAFKA_SERVICE: 'localhost:9092'
  KAFKA_TOPIC: 'cve'
  KAFKA_CONSUMER_GROUP_ID: 'llm-ingestor'
  KAFKA_MAX_SIZE: '10000000'
  PORT: '3001'
  LLAMAINDEX_OLLAMA_BASE_URL: 'http://localhost:11434'
  LLAMAINDEX_MODEL_NAME: 'gemma:2b'
  EMBEDDING_DIM: '1024'
  LLAMAINDEX_EMBEDDING_MODEL_NAME: 'mxbai-embed-large:latest'

initContainers:
  - name: 'db-migrate'
    repository: marlapativ/db-migration
    tag: 'latest'
    pullPolicy: Always
    command: ['flyway']
    args: ['migrate']
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 25Mi

extraSecrets: {}

pod:
  readinessProbe:
    path: /healthz
  livenessProbe:
    path: /healthz

resources:
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 256Mi

podLabels: {}

podAnnotations: {}

serviceAccount:
  create: true
  name: 'llm-ingestor-sa'
  automount: false
  annotations: {}

db:
  secrets:
    postgresUsername: ''
    postgresPassword: ''
    username: ''
    password: ''
    database: ''
  config:
    host: ''
    port: '5432'
    table: 'embeddings'
    schema: 'cve'

kafka:
  secrets:
    username: ''
    password: ''

replicaCount: 3

image:
  repository: marlapativ/llm-ingestor
  tag: 'latest'
  pullPolicy: Always

affinity:
  enable: true
  topologyKey: topology.kubernetes.io/zone

pdb:
  create: true
  minAvailable: 1
  maxUnavailable: {}

autoscaling:
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 5
    targetMemory: 80
    annotations: {}
