FROM python:3.11-slim-bookworm as base

RUN apt-get update && \
    apt-get install -y gcc build-essential curl git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install uv
RUN uv pip install --system -r requirements.txt --no-cache-dir

COPY . .

ENTRYPOINT [ "python3", "--version" ]
