FROM ghcr.io/open-webui/pipelines AS base

COPY ./requirements.txt ./pipeline-requirements.txt

RUN pip3 install uv
RUN uv pip install --system -r pipeline-requirements.txt --no-cache-dir

COPY ./pipeline.py ./pipelines/cve_pipeline.py
