apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-ingestor.fullname" . }}-consumer-configmap
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "llm-ingestor.labels" . | nindent 4 }}
data:
  RELEASE_NAME: {{ .Release.Name }}
  DB_HOST: {{ include "llm-ingestor.database.hostname" . }}
  {{- toYaml .Values.env | nindent 2 }}
